spring:
  datasource:
    username: postgres
    url: jdbc:postgresql://localhost:5432/organizationDatabase
    driverClassName: org.postgresql.Driver
    password: '1234'
  jpa:
    properties:
      hibernate:
        dialect: org.hibernate.dialect.PostgreSQLDialect
    database-platform: org.hibernate.dialect.PostgreSQLDialect
    hibernate:
      ddl-auto: update
    show-sql: 'true'
logging:
  level:
    org:
      hibernate:
        type: trace
        #SQL: debug
  file:
     name: app.log
  pattern:
        file: '%d [%level] %c{1.} [%t] %m%n'
server:
  port: 8080
app:
  key: 77397A24432646294A404E635266546A576E5A7234753778214125442A472D4B
elasticemail.api-key: EBD95D3C3D8FBDB020C2EB48743F16066D1B6661E36F9A7718A03F03D5A6205FEBC925E97BC9D27900907B6CDDD7AB94

   
    
 
