spring:
  datasource:
    username: postgres
    url: jdbc:postgresql://localhost:5432/organizationDatabase
    driverClassName: org.postgresql.Driver
    password: '1234'
  jpa:
    properties:
      hibernate:
        dialect: org.hibernate.dialect.PostgreSQLDialect
    database-platform: org.hibernate.dialect.PostgreSQLDialect
    hibernate:
      ddl-auto: update
    show-sql: 'true'
logging:
  level:
    org:
      hibernate:
        type: trace
        SQL: debug
server:
  port: 9090
app:
  key: 77397A24432646294A404E635266546A576E5A7234753778214125442A472D4B
