spring:
  datasource:
    username: postgres
    url: jdbc:postgresql://localhost:5432/employeeManagement
    driverClassName: org.postgresql.Driver
    password: '1234'
  jpa:
    properties:
      hibernate:
        dialect: org.hibernate.dialect.PostgreSQLDialect
    database-platform: org.hibernate.dialect.PostgreSQLDialect
    hibernate:
      ddl-auto: update
    show-sql: 'true'
logging:
  level:
    org:
      hibernate:
        type: trace
        SQL: debug
